### ISSUE TITLE
Show "Board details not available. Compile the sketch once." when click upload

### ISSUE THREAD

**Issue by Metaphorme** [earlephilhower/arduino-littlefs-upload#3]
Sorry for bothering you again...

I had set fqbn and I could compile and upload my firmware. But when I tried to update files into LittleFS, it shows "Board details not available. Compile the sketch once.".

I tried to know what it means and found something [here](https://github.com/earlephilhower/arduino-littlefs-upload/blob/main/src/extension.ts#L74) :

```typescript
if ((arduinoContext.boardDetails === undefined) ||  (arduinoContext.fqbn === undefined)){
    vscode.window.showErrorMessage("Board details not available. Compile the sketch once.");
    return;
}
```

I'm sure that I have set my fqbn, but I don't know how to set `arduinoContext.boardDetails`. Maybe this problem has to do with [this](https://github.com/dankeboy36/vscode-arduino-api/issues/6)?

fqbn had set:

<img width="390" alt="截屏2023-10-25 01 32 01" src="https://github.com/earlephilhower/arduino-littlefs-upload/assets/102651183/43ea2631-e93d-454c-8f40-e74840d5d833">

boardDetails had set(maybe):

<img width="489" alt="截屏2023-10-25 01 33 00" src="https://github.com/earlephilhower/arduino-littlefs-upload/assets/102651183/da591a8e-3705-422f-a12e-b7cbda309096">

Tools -> Get board info:

<img width="253" alt="截屏2023-10-25 01 34 02" src="https://github.com/earlephilhower/arduino-littlefs-upload/assets/102651183/51c5bc64-0b1d-4ce5-aa93-8a83854f2e89">

Thanks for your help! 

Have a nice day! :)

**Comment by earlephilhower** [comment]
Please see the readme about the bug in the IDE and workaround when this happens.

**Comment by Metaphorme** [comment]
Solution: https://github.com/earlephilhower/arduino-littlefs-upload#glitches

Thanks! It never occurred to me that these two things could be so mysteriously related.

**Comment by reivaxy** [comment]
@Metaphorme to me neither, thanks for creating this issue!
@earlephilhower It might help to add the error message "Board details not available. Compile the sketch once." in the glitches paragraph, what do you think?

**Comment by earlephilhower** [comment]
@reivaxy I'm sorry, but I don't quite understand your suggestion.  Why not make a PR (for text docs like this you can do it right from the GH website) to make it clear?

**Comment by Quantummechanic1** [comment]
This issue still exists in Arduino IDE 2.3.4 

![Image](https://github.com/user-attachments/assets/867f29c0-8dda-49c5-adda-6d9f45921231)

@earlephilhower the suggestion by @reivaxy is to add the error message in the readme, so that a Google search will lead to that particular paragraph.

BTW, I opened the IDE (on Win10) by double clicking on the .ino file. The sketch compiled and uploaded successfully, but the Upload LittleFS failed with "Board details not available. Compile the sketch once.". 
A re-compile did not solve. A change of board and back and re-compile, as suggested, resulted in another error (sketch path and data path undefined).
For me, the problems were solved by opening another sketch (via File->Open recent), close the failing sketch, re-open and close the other sketch (i.e. there is finally only one IDE running).
