### ISSUE TITLE
Extension doesn't work in vscode

### ISSUE THREAD

**Issue by SpintroniK** [earlephilhower/arduino-littlefs-upload#57]
I don't know if that's even possible, but I'm trying to use the extension in vscode.
The installation was successful, and everything else works.
I use the Arduino Community Edition extension, which build my sketch successfully.

The LittleFS Upload extension works perfectly in the Arduino IDE.
But using the same sketch in vscode, the extension fails to execute, and show the following error:
![image](https://github.com/user-attachments/assets/c257982d-9566-4e6a-b06c-fe8ed379cce7)
Is it possible to make the extension work within vscode?

Thanks.

**Comment by earlephilhower** [comment]
I highly doubt this will ever run in VSCode, even if you could get it to recognize the extension.  The issue is the Arduino-specific variables that it needs access to are not going to be set by VSCode.  Without that information, it can't actually do anything.

You can always manually build and upload filesystems from the command line (maybe script it and add a menu item in vscode?).  For examples, you can run the IDE proper, do an upload, and cut-n-paste the command lines it shows.
